### PR TITLE
Add prefix to mbtiles, return 204 on no tile

### PR DESCRIPTION
**Pull request by mtfurlan**
This adds a configuration option for a prefix to the mbtiles, so you can
store the tiles in other locations.

It also changes the no tile found 404 to a 204, as the mapbox team will
be doing:
https://github.com/mapbox/mapbox-gl-js/issues/1800#issuecomment-236190808

### CODE REVIEW

**Comment by daliborjanak** [comment]
Looks good. Thanks, but I would like to rename the variable `mbtilesPrefix` to something better. We are planning to add geopackage support in next days so it could be something like `dataPath`, `dataSource` or `dataDir`. What do you thing?

**Comment by mtfurlan** [comment]
I would vote for `dataSource`, or maybe `dataDir`.

**Comment by klokan** [comment]
In our TileServer GL it is called root path  - see JSON config at http://tileserver.readthedocs.io/en/latest/config.html

**Comment by daliborjanak** [comment]
I'm prefering data*. Root is often used as root of an app. But this variable as to be used also for folder structures - with serving without htaccess...

**Comment by klokan** [comment]
`dataRoot`?

**Comment by mtfurlan** [comment]
`dataRoot` would work, it's still clear as to what it does.

**Comment by mtfurlan** [comment]
It's still `mbtilesPrefix`?

**Comment by daliborjanak** [comment]
https://github.com/klokantech/tileserver-php/commit/2ead30dc4a811308c17345068ab341b1a37f1b4a

**Comment by mtfurlan** [comment]
Fair enough.
Many thanks!

**Pull request merged**
